### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by pattiereaves** [99xt/react-scaffolder#29] opened 2017-07-12 20:17 UTC
### expected behaviour
After running 

```
npm install -g react-scaffolder
react v -c
```

I get the error
```
env: node\r: No such file or directory
```

### steps to reproduce the problem.

See above

### specifications like the version of the project, operating system, or hardware.

I'm running npm@5.1.0 and node@6.10.3 on macOS@10.12.5

**Comment by rajikaimal** [comment] 2017-07-13 10:29
Hi, did you follow the [quick start guide](https://github.com/99xt/react-scaffolder#quick-start) ?

**Comment by rajikaimal** [comment] 2017-07-13 10:31
First you should create a project with `init` command, or you should use the CLI with an existing project by configuring `.reactclirc` file

**Comment by rajikaimal** [comment] 2017-07-26 14:22
@pattiereaves Since I couldn't reproduce this, I'll close this for now. If you come up with any way to reproduce this, please feel free to reopen the issue.

**Closed by rajikaimal** 2017-07-26 14:22 UTC

**Comment by zaguiini** [comment] 2018-05-23 22:58
+1
